/* 
 * File:	C:\Users\shun\JUMBLEQ\SigmaDSP\exported_code\JUMBLEQ_DSP_ADAU146xSchematic_1_PARAM.h
 * Created:	Tuesday, 21 April 2026 22:13 PM
 * Description:	ADAU146xSchematic_1 parameter RAM definitions.
 * 
 * This software is distributed in the hope that it will be useful, 
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * 
 * This software may only be used to program products purchased from 
 * Analog Devices for incorporation by you into audio products that 
 * are intended for resale to audio product end users.This software 
 * may not be distributed whole or in any part to third parties. 
 * 
 * Copyright © 2026 Analog Devices, Inc. All rights reserved.
 */
#ifndef __JUMBLEQ_DSP_ADAU146XSCHEMATIC_1_PARAM_H__
#define __JUMBLEQ_DSP_ADAU146XSCHEMATIC_1_PARAM_H__

/* Module Safeload - Schematic Params */
#define MOD_SAFELOAD_COUNT                          8
#define MOD_SAFELOAD_SCHEMATIC                      "ADAU146xSchematic_1"
#define MOD_SAFELOAD_DATA_SAFELOAD0_ADDR            24576
#define MOD_SAFELOAD_DATA_SAFELOAD0_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD1_ADDR            24577
#define MOD_SAFELOAD_DATA_SAFELOAD1_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD2_ADDR            24578
#define MOD_SAFELOAD_DATA_SAFELOAD2_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD3_ADDR            24579
#define MOD_SAFELOAD_DATA_SAFELOAD3_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD4_ADDR            24580
#define MOD_SAFELOAD_DATA_SAFELOAD4_MEM_PAGE        0
#define MOD_SAFELOAD_ADDR_SAFELOAD_ADDR             24581
#define MOD_SAFELOAD_ADDR_SAFELOAD_MEM_PAGE         0
#define MOD_SAFELOAD_NUM_SAFELOAD_LOWER_ADDR        24582
#define MOD_SAFELOAD_NUM_SAFELOAD_LOWER_MEM_PAGE    0
#define MOD_SAFELOAD_NUM_SAFELOAD_UPPER_ADDR        24583
#define MOD_SAFELOAD_NUM_SAFELOAD_UPPER_MEM_PAGE    0




/* Module input_from_ch2 - Single Volume Control */
#define MOD_INPUT_FROM_CH2_COUNT               1
#define MOD_INPUT_FROM_CH2_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_CH2_GAIN_ADDR           130
#define MOD_INPUT_FROM_CH2_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_CH2_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_CH2_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_CH2_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH2_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_CH2_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH2_GAIN_MEM_PAGE       0






/* Module DCInput_B - DC Input */
#define MOD_DCINPUT_B_COUNT                  1
#define MOD_DCINPUT_B_SCHEMATIC              "ADAU146xSchematic_1"
#define MOD_DCINPUT_B_DCVALUE_ADDR           118
#define MOD_DCINPUT_B_DCVALUE_FIXPT          0x00000000
#define MOD_DCINPUT_B_DCVALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_DCINPUT_B_DCVALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DCINPUT_B_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_B_DCVALUE_MEM_PAGE       0
#define MOD_DCINPUT_B_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_B_DCVALUE_MEM_PAGE       0

/* Module Ln_Pn_SW_1 - 2xN Switch */
#define MOD_LN_PN_SW_1_COUNT                         2
#define MOD_LN_PN_SW_1_SCHEMATIC                     "ADAU146xSchematic_1"
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_ADDR           110
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_FIXPT          0x01000000
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_1_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_ADDR           111
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_FIXPT          0x00000000
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_MEM_PAGE       0
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_1_INDEX_CHANNEL1_MEM_PAGE       0

/* Module SignalMerger_1L - Signal Merger */
#define MOD_SIGNALMERGER_1L_COUNT               1
#define MOD_SIGNALMERGER_1L_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_1L_GAIN_ADDR           132
#define MOD_SIGNALMERGER_1L_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_1L_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_1L_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_1L_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_1L_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_1L_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_1L_GAIN_MEM_PAGE       0

/* Module SignalMerger_1R - Signal Merger */
#define MOD_SIGNALMERGER_1R_COUNT               1
#define MOD_SIGNALMERGER_1R_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_1R_GAIN_ADDR           134
#define MOD_SIGNALMERGER_1R_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_1R_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_1R_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_1R_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_1R_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_1R_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_1R_GAIN_MEM_PAGE       0

/* Module Ph_EQ_Gain_1 - Single Volume Control */
#define MOD_PH_EQ_GAIN_1_COUNT               1
#define MOD_PH_EQ_GAIN_1_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_PH_EQ_GAIN_1_GAIN_ADDR           131
#define MOD_PH_EQ_GAIN_1_GAIN_FIXPT          0x02D1818B
#define MOD_PH_EQ_GAIN_1_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(2.81838293126445)
#define MOD_PH_EQ_GAIN_1_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_GAIN_1_GAIN_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_GAIN_1_GAIN_MEM_PAGE       0
#define MOD_PH_EQ_GAIN_1_GAIN_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_GAIN_1_GAIN_MEM_PAGE       0

/* Module SingleSlewExtVol_B - External Volume Control (Slew) */
#define MOD_SINGLESLEWEXTVOL_B_COUNT                    1
#define MOD_SINGLESLEWEXTVOL_B_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_ADDR           24591
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_FIXPT          0x0000208A
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_MEM_PAGE       0
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_B_SLEW_MODE_MEM_PAGE       0

/* Module DCInput_A - DC Input */
#define MOD_DCINPUT_A_COUNT                  1
#define MOD_DCINPUT_A_SCHEMATIC              "ADAU146xSchematic_1"
#define MOD_DCINPUT_A_DCVALUE_ADDR           117
#define MOD_DCINPUT_A_DCVALUE_FIXPT          0x00000000
#define MOD_DCINPUT_A_DCVALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_DCINPUT_A_DCVALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DCINPUT_A_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_A_DCVALUE_MEM_PAGE       0
#define MOD_DCINPUT_A_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_A_DCVALUE_MEM_PAGE       0

/* Module SingleSlewExtVol_A - External Volume Control (Slew) */
#define MOD_SINGLESLEWEXTVOL_A_COUNT                    1
#define MOD_SINGLESLEWEXTVOL_A_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_ADDR           24587
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_FIXPT          0x0000208A
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_MEM_PAGE       0
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_A_SLEW_MODE_MEM_PAGE       0

/* Module SignalMerger_2 - Signal Merger */
#define MOD_SIGNALMERGER_2_COUNT               1
#define MOD_SIGNALMERGER_2_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_2_GAIN_ADDR           167
#define MOD_SIGNALMERGER_2_GAIN_FIXPT          0x00400000004000000040000000400000
#define MOD_SIGNALMERGER_2_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_2_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2_GAIN_MEM_PAGE       0

/* Module SignalMerger_3 - Signal Merger */
#define MOD_SIGNALMERGER_3_COUNT               1
#define MOD_SIGNALMERGER_3_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_3_GAIN_ADDR           162
#define MOD_SIGNALMERGER_3_GAIN_FIXPT          0x00400000004000000040000000400000
#define MOD_SIGNALMERGER_3_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_3_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_3_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_3_GAIN_MEM_PAGE       0

/* Module input_from_ch1 - Single Volume Control */
#define MOD_INPUT_FROM_CH1_COUNT               1
#define MOD_INPUT_FROM_CH1_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_CH1_GAIN_ADDR           136
#define MOD_INPUT_FROM_CH1_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_CH1_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_CH1_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_CH1_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH1_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_CH1_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH1_GAIN_MEM_PAGE       0

/* Module ch1_output - Single Volume Control */
#define MOD_CH1_OUTPUT_COUNT               1
#define MOD_CH1_OUTPUT_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_CH1_OUTPUT_GAIN_ADDR           175
#define MOD_CH1_OUTPUT_GAIN_FIXPT          0x01000000
#define MOD_CH1_OUTPUT_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_CH1_OUTPUT_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_CH1_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_CH1_OUTPUT_GAIN_MEM_PAGE       0
#define MOD_CH1_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_CH1_OUTPUT_GAIN_MEM_PAGE       0

/* Module Ln_Pn_SW_2 - 2xN Switch */
#define MOD_LN_PN_SW_2_COUNT                         2
#define MOD_LN_PN_SW_2_SCHEMATIC                     "ADAU146xSchematic_1"
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_ADDR           82
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_FIXPT          0x01000000
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_2_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_ADDR           83
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_FIXPT          0x00000000
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_MEM_PAGE       0
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_2_INDEX_CHANNEL1_MEM_PAGE       0

/* Module SignalMerger_2L - Signal Merger */
#define MOD_SIGNALMERGER_2L_COUNT               1
#define MOD_SIGNALMERGER_2L_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_2L_GAIN_ADDR           126
#define MOD_SIGNALMERGER_2L_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_2L_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_2L_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_2L_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2L_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_2L_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2L_GAIN_MEM_PAGE       0

/* Module SignalMerger_2R - Signal Merger */
#define MOD_SIGNALMERGER_2R_COUNT               1
#define MOD_SIGNALMERGER_2R_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_2R_GAIN_ADDR           128
#define MOD_SIGNALMERGER_2R_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_2R_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_2R_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_2R_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2R_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_2R_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2R_GAIN_MEM_PAGE       0

/* Module Ph_EQ_Gain_2 - Single Volume Control */
#define MOD_PH_EQ_GAIN_2_COUNT               1
#define MOD_PH_EQ_GAIN_2_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_PH_EQ_GAIN_2_GAIN_ADDR           125
#define MOD_PH_EQ_GAIN_2_GAIN_FIXPT          0x02D1818B
#define MOD_PH_EQ_GAIN_2_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(2.81838293126445)
#define MOD_PH_EQ_GAIN_2_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_GAIN_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_GAIN_2_GAIN_MEM_PAGE       0
#define MOD_PH_EQ_GAIN_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_GAIN_2_GAIN_MEM_PAGE       0

/* Module SingleControlSplitter_2 - Single Control Splitter */
#define MOD_SINGLECONTROLSPLITTER_2_COUNT               1
#define MOD_SINGLECONTROLSPLITTER_2_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_ADDR           171
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_FIXPT          0x01000000
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_MEM_PAGE       0
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_SINGLECONTROLSPLITTER_2_GAIN_MEM_PAGE       0

/* Module SingleControlSplitter_3 - Single Control Splitter */
#define MOD_SINGLECONTROLSPLITTER_3_COUNT               1
#define MOD_SINGLECONTROLSPLITTER_3_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_ADDR           166
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_FIXPT          0x01000000
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_MEM_PAGE       0
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SINGLECONTROLSPLITTER_3_GAIN_MEM_PAGE       0

/* Module SignalMerger_B - Signal Merger */
#define MOD_SIGNALMERGER_B_COUNT               1
#define MOD_SIGNALMERGER_B_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_B_GAIN_ADDR           151
#define MOD_SIGNALMERGER_B_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_B_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_B_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_B_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_B_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_B_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_B_GAIN_MEM_PAGE       0

/* Module DSPReadBack_B - DSP Readback */
#define MOD_DSPREADBACK_B_COUNT                1
#define MOD_DSPREADBACK_B_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_DSPREADBACK_B_VALUE_ADDR           73
#define MOD_DSPREADBACK_B_VALUE_FIXPT          0x01000000
#define MOD_DSPREADBACK_B_VALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DSPREADBACK_B_VALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DSPREADBACK_B_VALUE_DATA_MEMORY    "DM0"
#define MOD_DSPREADBACK_B_VALUE_MEM_PAGE       0
#define MOD_DSPREADBACK_B_VALUE_DATA_MEMORY    "DM0"
#define MOD_DSPREADBACK_B_VALUE_MEM_PAGE       0

/* Module RunningAverage_B - Running Average */
#define MOD_RUNNINGAVERAGE_B_COUNT                      3
#define MOD_RUNNINGAVERAGE_B_SCHEMATIC                  "ADAU146xSchematic_1"
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_ADDR           153
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_FIXPT          0x000012DE
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.000287864561677509)
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_DATA_MEMORY    "DM0"
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_MEM_PAGE       0
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_DATA_MEMORY    "DM0"
#define MOD_RUNNINGAVERAGE_B_RMSTCINDBPS_MEM_PAGE       0
#define MOD_RUNNINGAVERAGE_B_DECAY_ADDR                 155
#define MOD_RUNNINGAVERAGE_B_DECAY_FIXPT                0x000000DA
#define MOD_RUNNINGAVERAGE_B_DECAY_VALUE                SIGMASTUDIOTYPE_8_24_CONVERT(1.30208333333333E-05)
#define MOD_RUNNINGAVERAGE_B_DECAY_TYPE                 SIGMASTUDIOTYPE_8_24
#define MOD_RUNNINGAVERAGE_B_DECAY_DATA_MEMORY          "DM0"
#define MOD_RUNNINGAVERAGE_B_DECAY_MEM_PAGE             0
#define MOD_RUNNINGAVERAGE_B_DECAY_DATA_MEMORY          "DM0"
#define MOD_RUNNINGAVERAGE_B_DECAY_MEM_PAGE             0
#define MOD_RUNNINGAVERAGE_B_HOLD_ADDR                  154
#define MOD_RUNNINGAVERAGE_B_HOLD_FIXPT                 0x00000000
#define MOD_RUNNINGAVERAGE_B_HOLD_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_RUNNINGAVERAGE_B_HOLD_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_RUNNINGAVERAGE_B_HOLD_DATA_MEMORY           "DM0"
#define MOD_RUNNINGAVERAGE_B_HOLD_MEM_PAGE              0
#define MOD_RUNNINGAVERAGE_B_HOLD_DATA_MEMORY           "DM0"
#define MOD_RUNNINGAVERAGE_B_HOLD_MEM_PAGE              0

/* Module xf_assign_sw_B - Nx2 Switch */
#define MOD_XF_ASSIGN_SW_B_COUNT                1
#define MOD_XF_ASSIGN_SW_B_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_XF_ASSIGN_SW_B_INDEX_ADDR           150
#define MOD_XF_ASSIGN_SW_B_INDEX_FIXPT          0x00000000
#define MOD_XF_ASSIGN_SW_B_INDEX_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_XF_ASSIGN_SW_B_INDEX_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_XF_ASSIGN_SW_B_INDEX_DATA_MEMORY    "DM0"
#define MOD_XF_ASSIGN_SW_B_INDEX_MEM_PAGE       0
#define MOD_XF_ASSIGN_SW_B_INDEX_DATA_MEMORY    "DM0"
#define MOD_XF_ASSIGN_SW_B_INDEX_MEM_PAGE       0

/* Module xf_assign_sw_A - Nx2 Switch */
#define MOD_XF_ASSIGN_SW_A_COUNT                1
#define MOD_XF_ASSIGN_SW_A_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_XF_ASSIGN_SW_A_INDEX_ADDR           138
#define MOD_XF_ASSIGN_SW_A_INDEX_FIXPT          0x00000001
#define MOD_XF_ASSIGN_SW_A_INDEX_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_XF_ASSIGN_SW_A_INDEX_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_XF_ASSIGN_SW_A_INDEX_DATA_MEMORY    "DM0"
#define MOD_XF_ASSIGN_SW_A_INDEX_MEM_PAGE       0
#define MOD_XF_ASSIGN_SW_A_INDEX_DATA_MEMORY    "DM0"
#define MOD_XF_ASSIGN_SW_A_INDEX_MEM_PAGE       0

/* Module xf_assign_sw_post - Nx2 Switch */
#define MOD_XF_ASSIGN_SW_POST_COUNT                1
#define MOD_XF_ASSIGN_SW_POST_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_XF_ASSIGN_SW_POST_INDEX_ADDR           137
#define MOD_XF_ASSIGN_SW_POST_INDEX_FIXPT          0x00000002
#define MOD_XF_ASSIGN_SW_POST_INDEX_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(2)
#define MOD_XF_ASSIGN_SW_POST_INDEX_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_XF_ASSIGN_SW_POST_INDEX_DATA_MEMORY    "DM0"
#define MOD_XF_ASSIGN_SW_POST_INDEX_MEM_PAGE       0
#define MOD_XF_ASSIGN_SW_POST_INDEX_DATA_MEMORY    "DM0"
#define MOD_XF_ASSIGN_SW_POST_INDEX_MEM_PAGE       0

/* Module SignalMerger_A - Signal Merger */
#define MOD_SIGNALMERGER_A_COUNT               1
#define MOD_SIGNALMERGER_A_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_A_GAIN_ADDR           139
#define MOD_SIGNALMERGER_A_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_A_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_A_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_A_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_A_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_A_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_A_GAIN_MEM_PAGE       0

/* Module DSPReadBack_A - DSP Readback */
#define MOD_DSPREADBACK_A_COUNT                1
#define MOD_DSPREADBACK_A_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_DSPREADBACK_A_VALUE_ADDR           64
#define MOD_DSPREADBACK_A_VALUE_FIXPT          0x01000000
#define MOD_DSPREADBACK_A_VALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DSPREADBACK_A_VALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DSPREADBACK_A_VALUE_DATA_MEMORY    "DM0"
#define MOD_DSPREADBACK_A_VALUE_MEM_PAGE       0
#define MOD_DSPREADBACK_A_VALUE_DATA_MEMORY    "DM0"
#define MOD_DSPREADBACK_A_VALUE_MEM_PAGE       0

/* Module RunningAverage_A - Running Average */
#define MOD_RUNNINGAVERAGE_A_COUNT                      3
#define MOD_RUNNINGAVERAGE_A_SCHEMATIC                  "ADAU146xSchematic_1"
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_ADDR           141
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_FIXPT          0x000012DE
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.000287864561677509)
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_DATA_MEMORY    "DM0"
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_MEM_PAGE       0
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_DATA_MEMORY    "DM0"
#define MOD_RUNNINGAVERAGE_A_RMSTCINDBPS_MEM_PAGE       0
#define MOD_RUNNINGAVERAGE_A_DECAY_ADDR                 143
#define MOD_RUNNINGAVERAGE_A_DECAY_FIXPT                0x000000DA
#define MOD_RUNNINGAVERAGE_A_DECAY_VALUE                SIGMASTUDIOTYPE_8_24_CONVERT(1.30208333333333E-05)
#define MOD_RUNNINGAVERAGE_A_DECAY_TYPE                 SIGMASTUDIOTYPE_8_24
#define MOD_RUNNINGAVERAGE_A_DECAY_DATA_MEMORY          "DM0"
#define MOD_RUNNINGAVERAGE_A_DECAY_MEM_PAGE             0
#define MOD_RUNNINGAVERAGE_A_DECAY_DATA_MEMORY          "DM0"
#define MOD_RUNNINGAVERAGE_A_DECAY_MEM_PAGE             0
#define MOD_RUNNINGAVERAGE_A_HOLD_ADDR                  142
#define MOD_RUNNINGAVERAGE_A_HOLD_FIXPT                 0x00000000
#define MOD_RUNNINGAVERAGE_A_HOLD_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_RUNNINGAVERAGE_A_HOLD_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_RUNNINGAVERAGE_A_HOLD_DATA_MEMORY           "DM0"
#define MOD_RUNNINGAVERAGE_A_HOLD_MEM_PAGE              0
#define MOD_RUNNINGAVERAGE_A_HOLD_DATA_MEMORY           "DM0"
#define MOD_RUNNINGAVERAGE_A_HOLD_MEM_PAGE              0

/* Module input_from_usb1 - Single Volume Control */
#define MOD_INPUT_FROM_USB1_COUNT               1
#define MOD_INPUT_FROM_USB1_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_USB1_GAIN_ADDR           122
#define MOD_INPUT_FROM_USB1_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_USB1_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_USB1_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_USB1_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB1_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_USB1_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB1_GAIN_MEM_PAGE       0

/* Module input_from_usb3 - Single Volume Control */
#define MOD_INPUT_FROM_USB3_COUNT               1
#define MOD_INPUT_FROM_USB3_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_USB3_GAIN_ADDR           121
#define MOD_INPUT_FROM_USB3_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_USB3_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_USB3_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_USB3_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB3_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_USB3_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB3_GAIN_MEM_PAGE       0



/* Module send2_output - Single Volume Control */
#define MOD_SEND2_OUTPUT_COUNT               1
#define MOD_SEND2_OUTPUT_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SEND2_OUTPUT_GAIN_ADDR           161
#define MOD_SEND2_OUTPUT_GAIN_FIXPT          0x01000000
#define MOD_SEND2_OUTPUT_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SEND2_OUTPUT_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SEND2_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_SEND2_OUTPUT_GAIN_MEM_PAGE       0
#define MOD_SEND2_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_SEND2_OUTPUT_GAIN_MEM_PAGE       0

/* Module DCInput_dryB - DC Input */
#define MOD_DCINPUT_DRYB_COUNT                  1
#define MOD_DCINPUT_DRYB_SCHEMATIC              "ADAU146xSchematic_1"
#define MOD_DCINPUT_DRYB_DCVALUE_ADDR           116
#define MOD_DCINPUT_DRYB_DCVALUE_FIXPT          0x01000000
#define MOD_DCINPUT_DRYB_DCVALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DCINPUT_DRYB_DCVALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DCINPUT_DRYB_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_DRYB_DCVALUE_MEM_PAGE       0
#define MOD_DCINPUT_DRYB_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_DRYB_DCVALUE_MEM_PAGE       0

/* Module SingleSlewExtVol_dryB - External Volume Control (Slew) */
#define MOD_SINGLESLEWEXTVOL_DRYB_COUNT                    1
#define MOD_SINGLESLEWEXTVOL_DRYB_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_ADDR           24593
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_FIXPT          0x0000208A
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_MEM_PAGE       0
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_DRYB_SLEW_MODE_MEM_PAGE       0

/* Module DCInput_wet - DC Input */
#define MOD_DCINPUT_WET_COUNT                  1
#define MOD_DCINPUT_WET_SCHEMATIC              "ADAU146xSchematic_1"
#define MOD_DCINPUT_WET_DCVALUE_ADDR           115
#define MOD_DCINPUT_WET_DCVALUE_FIXPT          0x01000000
#define MOD_DCINPUT_WET_DCVALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DCINPUT_WET_DCVALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DCINPUT_WET_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_WET_DCVALUE_MEM_PAGE       0
#define MOD_DCINPUT_WET_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_WET_DCVALUE_MEM_PAGE       0

/* Module SingleSlewExtVol_wet - External Volume Control (Slew) */
#define MOD_SINGLESLEWEXTVOL_WET_COUNT                    1
#define MOD_SINGLESLEWEXTVOL_WET_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_ADDR           24585
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_FIXPT          0x0000208A
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_MEM_PAGE       0
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_WET_SLEW_MODE_MEM_PAGE       0

/* Module DCInput_dryA - DC Input */
#define MOD_DCINPUT_DRYA_COUNT                  1
#define MOD_DCINPUT_DRYA_SCHEMATIC              "ADAU146xSchematic_1"
#define MOD_DCINPUT_DRYA_DCVALUE_ADDR           114
#define MOD_DCINPUT_DRYA_DCVALUE_FIXPT          0x01000000
#define MOD_DCINPUT_DRYA_DCVALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DCINPUT_DRYA_DCVALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DCINPUT_DRYA_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_DRYA_DCVALUE_MEM_PAGE       0
#define MOD_DCINPUT_DRYA_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_DRYA_DCVALUE_MEM_PAGE       0

/* Module SingleSlewExtVol_dryA - External Volume Control (Slew) */
#define MOD_SINGLESLEWEXTVOL_DRYA_COUNT                    1
#define MOD_SINGLESLEWEXTVOL_DRYA_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_ADDR           24589
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_FIXPT          0x0000208A
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_MEM_PAGE       0
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_DRYA_SLEW_MODE_MEM_PAGE       0

/* Module DVS_SW_1 - 2xN Switch */
#define MOD_DVS_SW_1_COUNT                         2
#define MOD_DVS_SW_1_SCHEMATIC                     "ADAU146xSchematic_1"
#define MOD_DVS_SW_1_INDEX_CHANNEL0_ADDR           112
#define MOD_DVS_SW_1_INDEX_CHANNEL0_FIXPT          0x01000000
#define MOD_DVS_SW_1_INDEX_CHANNEL0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DVS_SW_1_INDEX_CHANNEL0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DVS_SW_1_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_1_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_DVS_SW_1_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_1_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_DVS_SW_1_INDEX_CHANNEL1_ADDR           113
#define MOD_DVS_SW_1_INDEX_CHANNEL1_FIXPT          0x00000000
#define MOD_DVS_SW_1_INDEX_CHANNEL1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_DVS_SW_1_INDEX_CHANNEL1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DVS_SW_1_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_1_INDEX_CHANNEL1_MEM_PAGE       0
#define MOD_DVS_SW_1_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_1_INDEX_CHANNEL1_MEM_PAGE       0

/* Module DVS_SW_2 - 2xN Switch */
#define MOD_DVS_SW_2_COUNT                         2
#define MOD_DVS_SW_2_SCHEMATIC                     "ADAU146xSchematic_1"
#define MOD_DVS_SW_2_INDEX_CHANNEL0_ADDR           108
#define MOD_DVS_SW_2_INDEX_CHANNEL0_FIXPT          0x01000000
#define MOD_DVS_SW_2_INDEX_CHANNEL0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DVS_SW_2_INDEX_CHANNEL0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DVS_SW_2_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_2_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_DVS_SW_2_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_2_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_DVS_SW_2_INDEX_CHANNEL1_ADDR           109
#define MOD_DVS_SW_2_INDEX_CHANNEL1_FIXPT          0x00000000
#define MOD_DVS_SW_2_INDEX_CHANNEL1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_DVS_SW_2_INDEX_CHANNEL1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DVS_SW_2_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_2_INDEX_CHANNEL1_MEM_PAGE       0
#define MOD_DVS_SW_2_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_DVS_SW_2_INDEX_CHANNEL1_MEM_PAGE       0

/* Module GenSecondOrder_0 - General EQ */
#define MOD_GENSECONDORDER_0_COUNT                    5
#define MOD_GENSECONDORDER_0_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_GENSECONDORDER_0_STAGE0_B0_ADDR           45
#define MOD_GENSECONDORDER_0_STAGE0_B0_FIXPT          0x0010B2C7
#define MOD_GENSECONDORDER_0_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.06522795)
#define MOD_GENSECONDORDER_0_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_0_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_B1_ADDR           44
#define MOD_GENSECONDORDER_0_STAGE0_B1_FIXPT          0x000089C6
#define MOD_GENSECONDORDER_0_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.00210223)
#define MOD_GENSECONDORDER_0_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_0_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_B2_ADDR           43
#define MOD_GENSECONDORDER_0_STAGE0_B2_FIXPT          0xFFEFD6FE
#define MOD_GENSECONDORDER_0_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.06312573)
#define MOD_GENSECONDORDER_0_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_0_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_A1_ADDR           47
#define MOD_GENSECONDORDER_0_STAGE0_A1_FIXPT          0x01DDEA82
#define MOD_GENSECONDORDER_0_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1.86685955)
#define MOD_GENSECONDORDER_0_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_0_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_A2_ADDR           46
#define MOD_GENSECONDORDER_0_STAGE0_A2_FIXPT          0xFF21F9A9
#define MOD_GENSECONDORDER_0_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.86728426)
#define MOD_GENSECONDORDER_0_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_0_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_A2_MEM_PAGE       0
#define MOD_GENSECONDORDER_0_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_0_STAGE0_A2_MEM_PAGE       0

/* Module GenSecondOrder_1 - General EQ */
#define MOD_GENSECONDORDER_1_COUNT                    5
#define MOD_GENSECONDORDER_1_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_GENSECONDORDER_1_STAGE0_B0_ADDR           35
#define MOD_GENSECONDORDER_1_STAGE0_B0_FIXPT          0x0010B2C7
#define MOD_GENSECONDORDER_1_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.06522795)
#define MOD_GENSECONDORDER_1_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_1_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_B1_ADDR           34
#define MOD_GENSECONDORDER_1_STAGE0_B1_FIXPT          0x000089C6
#define MOD_GENSECONDORDER_1_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.00210223)
#define MOD_GENSECONDORDER_1_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_1_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_B2_ADDR           33
#define MOD_GENSECONDORDER_1_STAGE0_B2_FIXPT          0xFFEFD6FE
#define MOD_GENSECONDORDER_1_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.06312573)
#define MOD_GENSECONDORDER_1_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_1_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_A1_ADDR           37
#define MOD_GENSECONDORDER_1_STAGE0_A1_FIXPT          0x01DDEA82
#define MOD_GENSECONDORDER_1_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1.86685955)
#define MOD_GENSECONDORDER_1_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_1_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_A2_ADDR           36
#define MOD_GENSECONDORDER_1_STAGE0_A2_FIXPT          0xFF21F9A9
#define MOD_GENSECONDORDER_1_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.86728426)
#define MOD_GENSECONDORDER_1_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_1_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_A2_MEM_PAGE       0
#define MOD_GENSECONDORDER_1_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_1_STAGE0_A2_MEM_PAGE       0

/* Module GenSecondOrder_2 - General EQ */
#define MOD_GENSECONDORDER_2_COUNT                    5
#define MOD_GENSECONDORDER_2_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_GENSECONDORDER_2_STAGE0_B0_ADDR           40
#define MOD_GENSECONDORDER_2_STAGE0_B0_FIXPT          0x00FFC35E
#define MOD_GENSECONDORDER_2_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.999074827623903)
#define MOD_GENSECONDORDER_2_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_2_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_B1_ADDR           39
#define MOD_GENSECONDORDER_2_STAGE0_B1_FIXPT          0xFE007944
#define MOD_GENSECONDORDER_2_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-1.99814965524781)
#define MOD_GENSECONDORDER_2_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_2_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_B2_ADDR           38
#define MOD_GENSECONDORDER_2_STAGE0_B2_FIXPT          0x00FFC35E
#define MOD_GENSECONDORDER_2_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.999074827623903)
#define MOD_GENSECONDORDER_2_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_2_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_A1_ADDR           42
#define MOD_GENSECONDORDER_2_STAGE0_A1_FIXPT          0x01FF86AE
#define MOD_GENSECONDORDER_2_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1.9981487993037)
#define MOD_GENSECONDORDER_2_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_2_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_A2_ADDR           41
#define MOD_GENSECONDORDER_2_STAGE0_A2_FIXPT          0xFF007935
#define MOD_GENSECONDORDER_2_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.998150511191915)
#define MOD_GENSECONDORDER_2_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_2_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_A2_MEM_PAGE       0
#define MOD_GENSECONDORDER_2_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_2_STAGE0_A2_MEM_PAGE       0

/* Module GenSecondOrder_3 - General EQ */
#define MOD_GENSECONDORDER_3_COUNT                    5
#define MOD_GENSECONDORDER_3_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_GENSECONDORDER_3_STAGE0_B0_ADDR           30
#define MOD_GENSECONDORDER_3_STAGE0_B0_FIXPT          0x00FFC35E
#define MOD_GENSECONDORDER_3_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.999074827623903)
#define MOD_GENSECONDORDER_3_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_3_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_B0_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_B1_ADDR           29
#define MOD_GENSECONDORDER_3_STAGE0_B1_FIXPT          0xFE007944
#define MOD_GENSECONDORDER_3_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-1.99814965524781)
#define MOD_GENSECONDORDER_3_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_3_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_B1_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_B2_ADDR           28
#define MOD_GENSECONDORDER_3_STAGE0_B2_FIXPT          0x00FFC35E
#define MOD_GENSECONDORDER_3_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.999074827623903)
#define MOD_GENSECONDORDER_3_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_3_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_B2_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_A1_ADDR           32
#define MOD_GENSECONDORDER_3_STAGE0_A1_FIXPT          0x01FF86AE
#define MOD_GENSECONDORDER_3_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1.9981487993037)
#define MOD_GENSECONDORDER_3_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_3_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_A1_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_A2_ADDR           31
#define MOD_GENSECONDORDER_3_STAGE0_A2_FIXPT          0xFF007935
#define MOD_GENSECONDORDER_3_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.998150511191915)
#define MOD_GENSECONDORDER_3_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_GENSECONDORDER_3_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_A2_MEM_PAGE       0
#define MOD_GENSECONDORDER_3_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_GENSECONDORDER_3_STAGE0_A2_MEM_PAGE       0

/* Module send1_output - Single Volume Control */
#define MOD_SEND1_OUTPUT_COUNT               1
#define MOD_SEND1_OUTPUT_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SEND1_OUTPUT_GAIN_ADDR           149
#define MOD_SEND1_OUTPUT_GAIN_FIXPT          0x01000000
#define MOD_SEND1_OUTPUT_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SEND1_OUTPUT_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SEND1_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_SEND1_OUTPUT_GAIN_MEM_PAGE       0
#define MOD_SEND1_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_SEND1_OUTPUT_GAIN_MEM_PAGE       0

/* Module input_from_return - Single Volume Control */
#define MOD_INPUT_FROM_RETURN_COUNT               1
#define MOD_INPUT_FROM_RETURN_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_RETURN_GAIN_ADDR           124
#define MOD_INPUT_FROM_RETURN_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_RETURN_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_RETURN_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_RETURN_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_RETURN_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_RETURN_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_RETURN_GAIN_MEM_PAGE       0

/* Module input_from_usb2 - Single Volume Control */
#define MOD_INPUT_FROM_USB2_COUNT               1
#define MOD_INPUT_FROM_USB2_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_USB2_GAIN_ADDR           119
#define MOD_INPUT_FROM_USB2_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_USB2_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_USB2_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_USB2_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB2_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_USB2_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB2_GAIN_MEM_PAGE       0

/* Module input_from_usb4 - Single Volume Control */
#define MOD_INPUT_FROM_USB4_COUNT               1
#define MOD_INPUT_FROM_USB4_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_USB4_GAIN_ADDR           120
#define MOD_INPUT_FROM_USB4_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_USB4_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_USB4_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_USB4_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB4_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_USB4_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB4_GAIN_MEM_PAGE       0

/* Module ch2_output - Single Volume Control */
#define MOD_CH2_OUTPUT_COUNT               1
#define MOD_CH2_OUTPUT_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_CH2_OUTPUT_GAIN_ADDR           174
#define MOD_CH2_OUTPUT_GAIN_FIXPT          0x01000000
#define MOD_CH2_OUTPUT_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_CH2_OUTPUT_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_CH2_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_CH2_OUTPUT_GAIN_MEM_PAGE       0
#define MOD_CH2_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_CH2_OUTPUT_GAIN_MEM_PAGE       0

/* Module return_ch_SW - Nx2 Switch */
#define MOD_RETURN_CH_SW_COUNT                1
#define MOD_RETURN_CH_SW_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_RETURN_CH_SW_INDEX_ADDR           123
#define MOD_RETURN_CH_SW_INDEX_FIXPT          0x00000001
#define MOD_RETURN_CH_SW_INDEX_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_RETURN_CH_SW_INDEX_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_RETURN_CH_SW_INDEX_DATA_MEMORY    "DM0"
#define MOD_RETURN_CH_SW_INDEX_MEM_PAGE       0
#define MOD_RETURN_CH_SW_INDEX_DATA_MEMORY    "DM0"
#define MOD_RETURN_CH_SW_INDEX_MEM_PAGE       0

/* Module send_sw_1 - Nx2 Switch */
#define MOD_SEND_SW_1_COUNT                1
#define MOD_SEND_SW_1_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_SEND_SW_1_INDEX_ADDR           148
#define MOD_SEND_SW_1_INDEX_FIXPT          0x00000000
#define MOD_SEND_SW_1_INDEX_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_SEND_SW_1_INDEX_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SEND_SW_1_INDEX_DATA_MEMORY    "DM0"
#define MOD_SEND_SW_1_INDEX_MEM_PAGE       0
#define MOD_SEND_SW_1_INDEX_DATA_MEMORY    "DM0"
#define MOD_SEND_SW_1_INDEX_MEM_PAGE       0

/* Module send_sw_2 - Nx2 Switch */
#define MOD_SEND_SW_2_COUNT                1
#define MOD_SEND_SW_2_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_SEND_SW_2_INDEX_ADDR           160
#define MOD_SEND_SW_2_INDEX_FIXPT          0x00000000
#define MOD_SEND_SW_2_INDEX_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_SEND_SW_2_INDEX_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SEND_SW_2_INDEX_DATA_MEMORY    "DM0"
#define MOD_SEND_SW_2_INDEX_MEM_PAGE       0
#define MOD_SEND_SW_2_INDEX_DATA_MEMORY    "DM0"
#define MOD_SEND_SW_2_INDEX_MEM_PAGE       0



/* Module hp_output - Single Volume Control */
#define MOD_HP_OUTPUT_COUNT               1
#define MOD_HP_OUTPUT_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_HP_OUTPUT_GAIN_ADDR           173
#define MOD_HP_OUTPUT_GAIN_FIXPT          0x01000000
#define MOD_HP_OUTPUT_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_HP_OUTPUT_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_HP_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_HP_OUTPUT_GAIN_MEM_PAGE       0
#define MOD_HP_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_HP_OUTPUT_GAIN_MEM_PAGE       0

/* Module hp_out_sw - Nx2 Switch */
#define MOD_HP_OUT_SW_COUNT                1
#define MOD_HP_OUT_SW_SCHEMATIC            "ADAU146xSchematic_1"
#define MOD_HP_OUT_SW_INDEX_ADDR           172
#define MOD_HP_OUT_SW_INDEX_FIXPT          0x00000003
#define MOD_HP_OUT_SW_INDEX_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(3)
#define MOD_HP_OUT_SW_INDEX_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_HP_OUT_SW_INDEX_DATA_MEMORY    "DM0"
#define MOD_HP_OUT_SW_INDEX_MEM_PAGE       0
#define MOD_HP_OUT_SW_INDEX_DATA_MEMORY    "DM0"
#define MOD_HP_OUT_SW_INDEX_MEM_PAGE       0

#endif
