#ifndef INC_APP_VERSION_H_
#define INC_APP_VERSION_H_

#include <stdint.h>

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 9
#define APP_VERSION_PATCH 4

#define APP_VERSION_STR_HELPER(x) #x
#define APP_VERSION_STR_VALUE(x)  APP_VERSION_STR_HELPER(x)

#define APP_VERSION_STR      APP_VERSION_STR_VALUE(APP_VERSION_MAJOR) "." APP_VERSION_STR_VALUE(APP_VERSION_MINOR) "." APP_VERSION_STR_VALUE(APP_VERSION_PATCH)
#define APP_VERSION_OLED_STR "ver" APP_VERSION_STR
#define APP_VERSION_USB_BCD  ((uint16_t) (((APP_VERSION_MAJOR & 0x0F) << 8) | ((APP_VERSION_MINOR & 0x0F) << 4) | (APP_VERSION_PATCH & 0x0F)))

#endif /* INC_APP_VERSION_H_ */
