/* 
 * File:	C:\Users\shuni\OTO_DEVICES\SigmaDSP\exported_code\oto_no_ita_dsp_ADAU146xSchematic_1_PARAM.h
 * Created:	Thursday, 11 December 2025 10:00 AM
 * Description:	ADAU146xSchematic_1 parameter RAM definitions.
 * 
 * This software is distributed in the hope that it will be useful, 
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
 * CONDITIONS OF ANY KIND, without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * 
 * This software may only be used to program products purchased from 
 * Analog Devices for incorporation by you into audio products that 
 * are intended for resale to audio product end users.This software 
 * may not be distributed whole or in any part to third parties. 
 * 
 * Copyright © 2025 Analog Devices, Inc. All rights reserved.
 */
#ifndef __OTO_NO_ITA_DSP_ADAU146XSCHEMATIC_1_PARAM_H__
#define __OTO_NO_ITA_DSP_ADAU146XSCHEMATIC_1_PARAM_H__

/* Module Safeload - Schematic Params */
#define MOD_SAFELOAD_COUNT                          8
#define MOD_SAFELOAD_SCHEMATIC                      "ADAU146xSchematic_1"
#define MOD_SAFELOAD_DATA_SAFELOAD0_ADDR            24576
#define MOD_SAFELOAD_DATA_SAFELOAD0_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD1_ADDR            24577
#define MOD_SAFELOAD_DATA_SAFELOAD1_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD2_ADDR            24578
#define MOD_SAFELOAD_DATA_SAFELOAD2_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD3_ADDR            24579
#define MOD_SAFELOAD_DATA_SAFELOAD3_MEM_PAGE        0
#define MOD_SAFELOAD_DATA_SAFELOAD4_ADDR            24580
#define MOD_SAFELOAD_DATA_SAFELOAD4_MEM_PAGE        0
#define MOD_SAFELOAD_ADDR_SAFELOAD_ADDR             24581
#define MOD_SAFELOAD_ADDR_SAFELOAD_MEM_PAGE         0
#define MOD_SAFELOAD_NUM_SAFELOAD_LOWER_ADDR        24582
#define MOD_SAFELOAD_NUM_SAFELOAD_LOWER_MEM_PAGE    0
#define MOD_SAFELOAD_NUM_SAFELOAD_UPPER_ADDR        24583
#define MOD_SAFELOAD_NUM_SAFELOAD_UPPER_MEM_PAGE    0




/* Module input_from_ch2 - Single Volume Control */
#define MOD_INPUT_FROM_CH2_COUNT               1
#define MOD_INPUT_FROM_CH2_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_CH2_GAIN_ADDR           95
#define MOD_INPUT_FROM_CH2_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_CH2_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_CH2_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_CH2_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH2_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_CH2_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH2_GAIN_MEM_PAGE       0






/* Module input_from_usb - Single Volume Control */
#define MOD_INPUT_FROM_USB_COUNT               1
#define MOD_INPUT_FROM_USB_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_USB_GAIN_ADDR           83
#define MOD_INPUT_FROM_USB_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_USB_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_USB_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_USB_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_USB_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_USB_GAIN_MEM_PAGE       0

/* Module DCInput_0 - DC Input */
#define MOD_DCINPUT_0_COUNT                  1
#define MOD_DCINPUT_0_SCHEMATIC              "ADAU146xSchematic_1"
#define MOD_DCINPUT_0_DCVALUE_ADDR           82
#define MOD_DCINPUT_0_DCVALUE_FIXPT          0x01000000
#define MOD_DCINPUT_0_DCVALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DCINPUT_0_DCVALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DCINPUT_0_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_0_DCVALUE_MEM_PAGE       0
#define MOD_DCINPUT_0_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_0_DCVALUE_MEM_PAGE       0

/* Module Ln_Pn_SW - 2xN Switch */
#define MOD_LN_PN_SW_COUNT                         2
#define MOD_LN_PN_SW_SCHEMATIC                     "ADAU146xSchematic_1"
#define MOD_LN_PN_SW_INDEX_CHANNEL0_ADDR           80
#define MOD_LN_PN_SW_INDEX_CHANNEL0_FIXPT          0x00000000
#define MOD_LN_PN_SW_INDEX_CHANNEL0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_LN_PN_SW_INDEX_CHANNEL0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_LN_PN_SW_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_LN_PN_SW_INDEX_CHANNEL0_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_INDEX_CHANNEL0_MEM_PAGE       0
#define MOD_LN_PN_SW_INDEX_CHANNEL1_ADDR           81
#define MOD_LN_PN_SW_INDEX_CHANNEL1_FIXPT          0x01000000
#define MOD_LN_PN_SW_INDEX_CHANNEL1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_LN_PN_SW_INDEX_CHANNEL1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_LN_PN_SW_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_INDEX_CHANNEL1_MEM_PAGE       0
#define MOD_LN_PN_SW_INDEX_CHANNEL1_DATA_MEMORY    "DM0"
#define MOD_LN_PN_SW_INDEX_CHANNEL1_MEM_PAGE       0

/* Module SignalMerger_0 - Signal Merger */
#define MOD_SIGNALMERGER_0_COUNT               1
#define MOD_SIGNALMERGER_0_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_0_GAIN_ADDR           85
#define MOD_SIGNALMERGER_0_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_0_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_0_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_0_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_0_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_0_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_0_GAIN_MEM_PAGE       0

/* Module SignalMerger_1 - Signal Merger */
#define MOD_SIGNALMERGER_1_COUNT               1
#define MOD_SIGNALMERGER_1_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_1_GAIN_ADDR           87
#define MOD_SIGNALMERGER_1_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_1_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_1_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_1_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_1_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_1_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_1_GAIN_MEM_PAGE       0

/* Module Ph_EQ - Graphical Parametric EQ */
#define MOD_PH_EQ_COUNT                    15
#define MOD_PH_EQ_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_PH_EQ_STAGE0_B2_ADDR           28
#define MOD_PH_EQ_STAGE0_B2_FIXPT          0x00F46438
#define MOD_PH_EQ_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.954654227074152)
#define MOD_PH_EQ_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_B2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_B2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_B2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_B1_ADDR           29
#define MOD_PH_EQ_STAGE0_B1_FIXPT          0xFE021CC5
#define MOD_PH_EQ_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-1.99174848837953)
#define MOD_PH_EQ_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_B1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_B1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_B1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_B0_ADDR           30
#define MOD_PH_EQ_STAGE0_B0_FIXPT          0x01097F75
#define MOD_PH_EQ_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1.03710108693933)
#define MOD_PH_EQ_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_B0_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_B0_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_B0_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_A2_ADDR           31
#define MOD_PH_EQ_STAGE0_A2_FIXPT          0xFF021C53
#define MOD_PH_EQ_STAGE0_A2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.991755314013482)
#define MOD_PH_EQ_STAGE0_A2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_A2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_A2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_A2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_A1_ADDR           32
#define MOD_PH_EQ_STAGE0_A1_FIXPT          0x01FDE33B
#define MOD_PH_EQ_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1.99174848837953)
#define MOD_PH_EQ_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_A1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE0_A1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE0_A1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_B2_ADDR           24586
#define MOD_PH_EQ_STAGE1_B2_FIXPT          0x00F58BFB
#define MOD_PH_EQ_STAGE1_B2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.959167179850826)
#define MOD_PH_EQ_STAGE1_B2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE1_B2_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_B2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_B2_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_B2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_B1_ADDR           24587
#define MOD_PH_EQ_STAGE1_B1_FIXPT          0xFE0D7233
#define MOD_PH_EQ_STAGE1_B1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-1.9474762312657)
#define MOD_PH_EQ_STAGE1_B1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE1_B1_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_B1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_B1_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_B1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_B0_ADDR           24588
#define MOD_PH_EQ_STAGE1_B0_FIXPT          0x00FD125E
#define MOD_PH_EQ_STAGE1_B0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.988561502107709)
#define MOD_PH_EQ_STAGE1_B0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE1_B0_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_B0_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_B0_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_B0_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_A2_ADDR           24589
#define MOD_PH_EQ_STAGE1_A2_FIXPT          0xFF0D61A7
#define MOD_PH_EQ_STAGE1_A2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.947728681958535)
#define MOD_PH_EQ_STAGE1_A2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE1_A2_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_A2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_A2_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_A2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_A1_ADDR           24590
#define MOD_PH_EQ_STAGE1_A1_FIXPT          0x01F28DCD
#define MOD_PH_EQ_STAGE1_A1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1.9474762312657)
#define MOD_PH_EQ_STAGE1_A1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE1_A1_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_A1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE1_A1_DATA_MEMORY    "DM1"
#define MOD_PH_EQ_STAGE1_A1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_B2_ADDR           33
#define MOD_PH_EQ_STAGE2_B2_FIXPT          0x0045029C
#define MOD_PH_EQ_STAGE2_B2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.26957105939467)
#define MOD_PH_EQ_STAGE2_B2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE2_B2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_B2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_B2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_B2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_B1_ADDR           34
#define MOD_PH_EQ_STAGE2_B1_FIXPT          0x0094F8F0
#define MOD_PH_EQ_STAGE2_B1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.58192350170784)
#define MOD_PH_EQ_STAGE2_B1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE2_B1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_B1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_B1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_B1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_B0_ADDR           35
#define MOD_PH_EQ_STAGE2_B0_FIXPT          0x00670222
#define MOD_PH_EQ_STAGE2_B0_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.402376321322912)
#define MOD_PH_EQ_STAGE2_B0_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE2_B0_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_B0_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_B0_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_B0_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_A2_ADDR           36
#define MOD_PH_EQ_STAGE2_A2_FIXPT          0x0053FB42
#define MOD_PH_EQ_STAGE2_A2_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0.328052619282417)
#define MOD_PH_EQ_STAGE2_A2_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE2_A2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_A2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_A2_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_A2_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_A1_ADDR           37
#define MOD_PH_EQ_STAGE2_A1_FIXPT          0xFF6B0710
#define MOD_PH_EQ_STAGE2_A1_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(-0.58192350170784)
#define MOD_PH_EQ_STAGE2_A1_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_PH_EQ_STAGE2_A1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_A1_MEM_PAGE       0
#define MOD_PH_EQ_STAGE2_A1_DATA_MEMORY    "DM0"
#define MOD_PH_EQ_STAGE2_A1_MEM_PAGE       0

/* Module SingleVolumeControl_3 - Single Volume Control */
#define MOD_SINGLEVOLUMECONTROL_3_COUNT               1
#define MOD_SINGLEVOLUMECONTROL_3_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_ADDR           84
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_FIXPT          0x0FD9539A
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(15.8489319246111)
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_MEM_PAGE       0
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SINGLEVOLUMECONTROL_3_GAIN_MEM_PAGE       0

/* Module SingleSlewExtVol_0 - External Volume Control (Slew) */
#define MOD_SINGLESLEWEXTVOL_0_COUNT                    1
#define MOD_SINGLESLEWEXTVOL_0_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_ADDR           24592
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_FIXPT          0x00002080
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(8320)
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_MEM_PAGE       0
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_0_SLEW_MODE_MEM_PAGE       0

/* Module DCInput_1 - DC Input */
#define MOD_DCINPUT_1_COUNT                  1
#define MOD_DCINPUT_1_SCHEMATIC              "ADAU146xSchematic_1"
#define MOD_DCINPUT_1_DCVALUE_ADDR           63
#define MOD_DCINPUT_1_DCVALUE_FIXPT          0x01000000
#define MOD_DCINPUT_1_DCVALUE_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_DCINPUT_1_DCVALUE_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_DCINPUT_1_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_1_DCVALUE_MEM_PAGE       0
#define MOD_DCINPUT_1_DCVALUE_DATA_MEMORY    "DM0"
#define MOD_DCINPUT_1_DCVALUE_MEM_PAGE       0

/* Module SingleSlewExtVol_1 - External Volume Control (Slew) */
#define MOD_SINGLESLEWEXTVOL_1_COUNT                    1
#define MOD_SINGLESLEWEXTVOL_1_SCHEMATIC                "ADAU146xSchematic_1"
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_ADDR           24585
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_FIXPT          0x00002080
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_VALUE          SIGMASTUDIOTYPE_INTEGER_CONVERT(8320)
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_TYPE           SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_MEM_PAGE       0
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_DATA_MEMORY    "DM1"
#define MOD_SINGLESLEWEXTVOL_1_SLEW_MODE_MEM_PAGE       0

/* Module SignalMerger_2 - Signal Merger */
#define MOD_SIGNALMERGER_2_COUNT               1
#define MOD_SIGNALMERGER_2_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_2_GAIN_ADDR           92
#define MOD_SIGNALMERGER_2_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_2_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_2_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_2_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_2_GAIN_MEM_PAGE       0

/* Module SignalMerger_3 - Signal Merger */
#define MOD_SIGNALMERGER_3_COUNT               1
#define MOD_SIGNALMERGER_3_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_SIGNALMERGER_3_GAIN_ADDR           90
#define MOD_SIGNALMERGER_3_GAIN_FIXPT          0x0080000000800000
#define MOD_SIGNALMERGER_3_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_SIGNALMERGER_3_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_SIGNALMERGER_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_3_GAIN_MEM_PAGE       0
#define MOD_SIGNALMERGER_3_GAIN_DATA_MEMORY    "DM0"
#define MOD_SIGNALMERGER_3_GAIN_MEM_PAGE       0

/* Module input_from_ch1 - Single Volume Control */
#define MOD_INPUT_FROM_CH1_COUNT               1
#define MOD_INPUT_FROM_CH1_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_INPUT_FROM_CH1_GAIN_ADDR           89
#define MOD_INPUT_FROM_CH1_GAIN_FIXPT          0x01000000
#define MOD_INPUT_FROM_CH1_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_INPUT_FROM_CH1_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_INPUT_FROM_CH1_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH1_GAIN_MEM_PAGE       0
#define MOD_INPUT_FROM_CH1_GAIN_DATA_MEMORY    "DM0"
#define MOD_INPUT_FROM_CH1_GAIN_MEM_PAGE       0

/* Module master_output - Single Volume Control */
#define MOD_MASTER_OUTPUT_COUNT               1
#define MOD_MASTER_OUTPUT_SCHEMATIC           "ADAU146xSchematic_1"
#define MOD_MASTER_OUTPUT_GAIN_ADDR           94
#define MOD_MASTER_OUTPUT_GAIN_FIXPT          0x01000000
#define MOD_MASTER_OUTPUT_GAIN_VALUE          SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_MASTER_OUTPUT_GAIN_TYPE           SIGMASTUDIOTYPE_8_24
#define MOD_MASTER_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_MASTER_OUTPUT_GAIN_MEM_PAGE       0
#define MOD_MASTER_OUTPUT_GAIN_DATA_MEMORY    "DM0"
#define MOD_MASTER_OUTPUT_GAIN_MEM_PAGE       0

#endif
