/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 Jerzy Kasenbreg
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

#ifndef USB_DESCRIPTORS_H_
#define USB_DESCRIPTORS_H_

enum
{
    // UAC2 Function 1: Speaker OUT (AC + AS OUT)
    ITF_NUM_AUDIO_CONTROL_OUT = 0,
    ITF_NUM_AUDIO_STREAMING_STEREO_OUT,

    // UAC2 Function 2: Mic IN (AC + AS IN)
    ITF_NUM_AUDIO_CONTROL_IN,
    ITF_NUM_AUDIO_STREAMING_STEREO_IN,

// USB-MIDI (Audio Class, MIDIStreaming). TinyUSB MIDI uses 2 interfaces.
#if 1  // CFG_TUD_MIDI
    ITF_NUM_MIDI,
    ITF_NUM_MIDI_STREAMING,
#endif

    ITF_NUM_TOTAL
};

// Number of interfaces per UAC2 function (IAD scope)
#define ITF_NUM_AUDIO_FUNC_OUT_N_ITF 2
#define ITF_NUM_AUDIO_FUNC_IN_N_ITF  2

//--------------------------------------------------------------------+
// UAC2 DESCRIPTOR TEMPLATES
//--------------------------------------------------------------------+

// Entity IDs (must be unique within the whole configuration)
// Function 1 (OUT)
#define UAC2_ENTITY_CLOCK_OUT                  0x04
#define UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL 0x01
#define UAC2_ENTITY_STEREO_OUT_FEATURE_UNIT   0x02
#define UAC2_ENTITY_STEREO_OUT_OUTPUT_TERMINAL 0x03
// Function 2 (IN)
#define UAC2_ENTITY_CLOCK_IN                   0x14
#define UAC2_ENTITY_STEREO_IN_INPUT_TERMINAL  0x11
#define UAC2_ENTITY_STEREO_IN_OUTPUT_TERMINAL 0x13

// Backward-compat alias used by existing control code.
#define UAC2_ENTITY_CLOCK UAC2_ENTITY_CLOCK_OUT

// Function 1: UAC2 Speaker OUT (4ch) + Feedback
#define TUD_AUDIO20_SPK_OUT_DESC_LEN (TUD_AUDIO20_DESC_IAD_LEN + TUD_AUDIO20_DESC_STD_AC_LEN + TUD_AUDIO20_DESC_CS_AC_LEN + TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(4) + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + TUD_AUDIO20_DESC_STD_AC_INT_EP_LEN + TUD_AUDIO20_DESC_STD_AS_LEN + TUD_AUDIO20_DESC_STD_AS_LEN + TUD_AUDIO20_DESC_CS_AS_INT_LEN + TUD_AUDIO20_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO20_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO20_DESC_CS_AS_ISO_EP_LEN + TUD_AUDIO20_DESC_STD_AS_ISO_FB_EP_LEN)

#define TUD_AUDIO20_SPK_OUT_DESCRIPTOR(_itf_ac, _itf_as, _stridx_out, _epout, _epfb, _epint) \
    TUD_AUDIO20_DESC_IAD((_itf_ac), ITF_NUM_AUDIO_FUNC_OUT_N_ITF, (_stridx_out)), \
        TUD_AUDIO20_DESC_STD_AC((_itf_ac), 0x01, (_stridx_out)), \
        TUD_AUDIO20_DESC_CS_AC(0x0200, AUDIO20_FUNC_MUSICAL_INSTRUMENT, TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(4) + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN, AUDIO20_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
        TUD_AUDIO20_DESC_CLK_SRC(UAC2_ENTITY_CLOCK_OUT, 3, 7, 0x00, (_stridx_out)), \
        TUD_AUDIO20_DESC_INPUT_TERM(UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, UAC2_ENTITY_CLOCK_OUT, 0x04, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0 * (AUDIO20_CTRL_R << AUDIO20_IN_TERM_CTRL_CONNECTOR_POS), (_stridx_out)), \
        TUD_AUDIO20_DESC_FEATURE_UNIT(UAC2_ENTITY_STEREO_OUT_FEATURE_UNIT, UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL, (_stridx_out), (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS)), \
        TUD_AUDIO20_DESC_OUTPUT_TERM(UAC2_ENTITY_STEREO_OUT_OUTPUT_TERMINAL, AUDIO_TERM_TYPE_OUT_GENERIC_SPEAKER, 0x00, UAC2_ENTITY_STEREO_OUT_FEATURE_UNIT, UAC2_ENTITY_CLOCK_OUT, 0x0000, (_stridx_out)), \
        TUD_AUDIO20_DESC_STD_AC_INT_EP((_epint), 0x01), \
        TUD_AUDIO20_DESC_STD_AS_INT((_itf_as), 0x00, 0x00, (_stridx_out)), \
        TUD_AUDIO20_DESC_STD_AS_INT((_itf_as), 0x01, 0x02, (_stridx_out)), \
        TUD_AUDIO20_DESC_CS_AS_INT(UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL, AUDIO20_CTRL_NONE, AUDIO20_FORMAT_TYPE_I, AUDIO20_DATA_FORMAT_TYPE_I_PCM, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, (_stridx_out)), \
        TUD_AUDIO20_DESC_TYPE_I_FORMAT(CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX), \
        TUD_AUDIO20_DESC_STD_AS_ISO_EP((_epout), (uint8_t) ((uint8_t) TUSB_XFER_ISOCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_ASYNCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_DATA), TUD_AUDIO_EP_SIZE(TUD_OPT_HIGH_SPEED, CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX), 0x01), \
        TUD_AUDIO20_DESC_CS_AS_ISO_EP(AUDIO20_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO20_CTRL_NONE, AUDIO20_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, 0x0001), \
        TUD_AUDIO20_DESC_STD_AS_ISO_FB_EP((_epfb), 4, TUD_OPT_HIGH_SPEED ? 4 : 1)

// Function 2: UAC2 Mic IN (4ch)
#define TUD_AUDIO20_MIC_IN_DESC_LEN (TUD_AUDIO20_DESC_IAD_LEN + TUD_AUDIO20_DESC_STD_AC_LEN + TUD_AUDIO20_DESC_CS_AC_LEN + TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + TUD_AUDIO20_DESC_STD_AC_INT_EP_LEN + TUD_AUDIO20_DESC_STD_AS_LEN + TUD_AUDIO20_DESC_STD_AS_LEN + TUD_AUDIO20_DESC_CS_AS_INT_LEN + TUD_AUDIO20_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO20_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO20_DESC_CS_AS_ISO_EP_LEN)

#define TUD_AUDIO20_MIC_IN_DESCRIPTOR(_itf_ac, _itf_as, _stridx_in, _epin, _epint) \
    TUD_AUDIO20_DESC_IAD((_itf_ac), ITF_NUM_AUDIO_FUNC_IN_N_ITF, (_stridx_in)), \
        TUD_AUDIO20_DESC_STD_AC((_itf_ac), 0x01, (_stridx_in)), \
        TUD_AUDIO20_DESC_CS_AC(0x0200, AUDIO20_FUNC_MICROPHONE, TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN, AUDIO20_CS_AS_INTERFACE_CTRL_LATENCY_POS), \
        TUD_AUDIO20_DESC_CLK_SRC(UAC2_ENTITY_CLOCK_IN, 3, 7, 0x00, (_stridx_in)), \
        TUD_AUDIO20_DESC_INPUT_TERM(UAC2_ENTITY_STEREO_IN_INPUT_TERMINAL, AUDIO_TERM_TYPE_IN_GENERIC_MIC, 0x00, UAC2_ENTITY_CLOCK_IN, 0x04, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, 0x00, 0 * (AUDIO20_CTRL_R << AUDIO20_IN_TERM_CTRL_CONNECTOR_POS), (_stridx_in)), \
        TUD_AUDIO20_DESC_OUTPUT_TERM(UAC2_ENTITY_STEREO_IN_OUTPUT_TERMINAL, AUDIO_TERM_TYPE_USB_STREAMING, 0x00, UAC2_ENTITY_STEREO_IN_INPUT_TERMINAL, UAC2_ENTITY_CLOCK_IN, 0x0000, (_stridx_in)), \
        TUD_AUDIO20_DESC_STD_AC_INT_EP((_epint), 0x01), \
        TUD_AUDIO20_DESC_STD_AS_INT((_itf_as), 0x00, 0x00, (_stridx_in)), \
        TUD_AUDIO20_DESC_STD_AS_INT((_itf_as), 0x01, 0x01, (_stridx_in)), \
        TUD_AUDIO20_DESC_CS_AS_INT(UAC2_ENTITY_STEREO_IN_OUTPUT_TERMINAL, AUDIO20_CTRL_NONE, AUDIO20_FORMAT_TYPE_I, AUDIO20_DATA_FORMAT_TYPE_I_PCM, CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_TX, AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, (_stridx_in)), \
        TUD_AUDIO20_DESC_TYPE_I_FORMAT(CFG_TUD_AUDIO_FUNC_2_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_2_FORMAT_1_RESOLUTION_TX), \
        TUD_AUDIO20_DESC_STD_AS_ISO_EP((_epin), (uint8_t) ((uint8_t) TUSB_XFER_ISOCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_ASYNCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_DATA), TUD_AUDIO_EP_SIZE(TUD_OPT_HIGH_SPEED, CFG_TUD_AUDIO_FUNC_2_MAX_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_2_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_2_N_CHANNELS_TX), 0x01), \
        TUD_AUDIO20_DESC_CS_AS_ISO_EP(AUDIO20_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, AUDIO20_CTRL_NONE, AUDIO20_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, 0x0000)

#endif
